### ISSUE TITLE
Release 0.0.3?

### ISSUE THREAD

**Issue by rwjblue** [HeroicEric/ember-group-by#7]
Current 0.0.2 is quite large, because it accidentally includes `tmp` in the `npm` package:

```
66429015        npm.v1    ember-group-by-0.0.2.tgz/tmp
```

See https://github.com/ember-cli/ember-cli/issues/4199#issuecomment-134204192

---

The underlying issue has already been fixed (by adding `tmp/` to `.npmignore`), but not released.

**Comment by rwjblue** [comment]
@HeroicEric - Mind releasing?

**Comment by HeroicEric** [comment]
@rwjblue 0.0.3 released :smiley:
